Feature/fh 69
funnelhub-io/typebot.io pull request #42
Opened 2024-03-27 19:31 UTC by henricker

# Envio de notificação quando o whatsapp se encontra expirado

- Quando o whatsapp ficar expirado ele irá enviar uma notificação para o hub e o hub terá a responsabilidade de enviar a notificação por email e via push

2024-03-28 09:46 UTC, dhanielo requested changes

2024-03-28 09:46 UTC, dhanielo commented on packages/bot-engine/whatsapp/WhatsappComponentFlow/sendWhatsappSocketMessage.ts
> +import { WhatsappSocketSendingMessage } from './convertMessageToWhatsappCompoent'
"Compoent"* -> "Component"

2024-03-28 09:46 UTC, dhanielo commented on packages/bot-engine/whatsapp/WhatsappComponentFlow/sendWhatsappSocketMessage.ts
> +  sessionId: string
pq antes era opcional?

2024-03-28 09:46 UTC, dhanielo commented on packages/bot-engine/whatsapp/WhatsappComponentFlow/sendWhatsappSocketMessage.ts
> +    description: `Olá ${member.name}, notamos que a sessão do whatsapp no typebot com nome ${typebotName} foi expirado, por favor, leia o qrcode novamente para evitar problemas com seu fluxo.`,
É possível incluir esse texto nas traduções?

2024-03-28 11:28 UTC, henricker commented on packages/bot-engine/whatsapp/WhatsappComponentFlow/sendWhatsappSocketMessage.ts
> +  sessionId: string
Nem sei kkkkkk, mas sempre passava o sessionId, meio que é obrigatório, por isso removi o optional chaining

2024-03-28 11:28 UTC, henricker commented on packages/bot-engine/whatsapp/WhatsappComponentFlow/sendWhatsappSocketMessage.ts
> +    description: `Olá ${member.name}, notamos que a sessão do whatsapp no typebot com nome ${typebotName} foi expirado, por favor, leia o qrcode novamente para evitar problemas com seu fluxo.`,
Posso, vou ajustar

2024-03-29 08:17 UTC, dhanielo commented on packages/bot-engine/whatsapp/WhatsappComponentFlow/sendWhatsappSocketMessage.ts
> +    description: `Olá ${member.name}, notamos que a sessão do whatsapp no typebot com nome ${typebotName} foi expirado, por favor, leia o qrcode novamente para evitar problemas com seu fluxo.`,
O Gabriel chegou a fazer uma implementação para o back-end, pode verificar com ele depois

2024-04-01 13:04 UTC, henricker commented on packages/bot-engine/whatsapp/WhatsappComponentFlow/sendWhatsappSocketMessage.ts
> +    description: `Olá ${member.name}, notamos que a sessão do whatsapp no typebot com nome ${typebotName} foi expirado, por favor, leia o qrcode novamente para evitar problemas com seu fluxo.`,
Problema do server side é que o pacote de traduções está dentro do builder.
E o pacote que estou mexendo é dentro da bot engines.
Só conseguiria utilizar se criar um novo pacote, por agora podemos deixar em pt-br e quando subir a demanda a gente cria um pacote novo só para as traduções..

2024-04-02 11:49 UTC, merged